/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as EternityIiRouteImport } from './routes/eternity-ii'
import { Route as TheTaberSquareRouteImport } from './routes/the-taber-square'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAuthRouteImport } from './routes/$lang/auth'
import { Route as LangEternityIiIndexRouteImport } from './routes/$lang/eternity-ii/index'
import { Route as LangEternityIiPlayRouteImport } from './routes/$lang/eternity-ii/play'
import { Route as LangTaberdokuIndexRouteImport } from './routes/$lang/taberdoku/index'
import { Route as LangTheTaberSquareIndexRouteImport } from './routes/$lang/the-taber-square/index'
import { Route as LangTheTaberSquarePlayRouteImport } from './routes/$lang/the-taber-square/play'
import { Route as LangTheTabersStarIndexRouteImport } from './routes/$lang/the-tabers-star/index'
import { Route as LangTheTabersStarPlayRouteImport } from './routes/$lang/the-tabers-star/play'
import { Route as LangTaberdokuMurdokuIndexRouteImport } from './routes/$lang/taberdoku/murdoku/index'
import { Route as LangTaberdokuMurdokuAdminRouteImport } from './routes/$lang/taberdoku/murdoku/admin'
import { Route as LangTaberdokuMurdokuCreateRouteImport } from './routes/$lang/taberdoku/murdoku/create'
import { Route as LangTaberdokuMurdokuPlayRouteImport } from './routes/$lang/taberdoku/murdoku/play'
import { Route as LangTaberdokuStarBattleIndexRouteImport } from './routes/$lang/taberdoku/star-battle/index'
import { Route as LangTaberdokuStarBattlePlayRouteImport } from './routes/$lang/taberdoku/star-battle/play'
import { Route as LangTaberdokuTabersSudokuIndexRouteImport } from './routes/$lang/taberdoku/tabers-sudoku/index'
import { Route as LangTaberdokuTabersSudokuPlayRouteImport } from './routes/$lang/taberdoku/tabers-sudoku/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const EternityIiRoute = EternityIiRouteImport.update({
  id: '/eternity-ii',
  path: '/eternity-ii',
  getParentRoute: () => rootRouteImport,
} as any)
const TheTaberSquareRoute = TheTaberSquareRouteImport.update({
  id: '/the-taber-square',
  path: '/the-taber-square',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAuthRoute = LangAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangEternityIiIndexRoute = LangEternityIiIndexRouteImport.update({
  id: '/eternity-ii/',
  path: '/eternity-ii/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangEternityIiPlayRoute = LangEternityIiPlayRouteImport.update({
  id: '/eternity-ii/play',
  path: '/eternity-ii/play',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTaberdokuIndexRoute = LangTaberdokuIndexRouteImport.update({
  id: '/taberdoku/',
  path: '/taberdoku/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTheTaberSquareIndexRoute = LangTheTaberSquareIndexRouteImport.update({
  id: '/the-taber-square/',
  path: '/the-taber-square/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTheTaberSquarePlayRoute = LangTheTaberSquarePlayRouteImport.update({
  id: '/the-taber-square/play',
  path: '/the-taber-square/play',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTheTabersStarIndexRoute = LangTheTabersStarIndexRouteImport.update({
  id: '/the-tabers-star/',
  path: '/the-tabers-star/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTheTabersStarPlayRoute = LangTheTabersStarPlayRouteImport.update({
  id: '/the-tabers-star/play',
  path: '/the-tabers-star/play',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTaberdokuMurdokuIndexRoute =
  LangTaberdokuMurdokuIndexRouteImport.update({
    id: '/taberdoku/murdoku/',
    path: '/taberdoku/murdoku/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuMurdokuAdminRoute =
  LangTaberdokuMurdokuAdminRouteImport.update({
    id: '/taberdoku/murdoku/admin',
    path: '/taberdoku/murdoku/admin',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuMurdokuCreateRoute =
  LangTaberdokuMurdokuCreateRouteImport.update({
    id: '/taberdoku/murdoku/create',
    path: '/taberdoku/murdoku/create',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuMurdokuPlayRoute =
  LangTaberdokuMurdokuPlayRouteImport.update({
    id: '/taberdoku/murdoku/play',
    path: '/taberdoku/murdoku/play',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuStarBattleIndexRoute =
  LangTaberdokuStarBattleIndexRouteImport.update({
    id: '/taberdoku/star-battle/',
    path: '/taberdoku/star-battle/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuStarBattlePlayRoute =
  LangTaberdokuStarBattlePlayRouteImport.update({
    id: '/taberdoku/star-battle/play',
    path: '/taberdoku/star-battle/play',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuTabersSudokuIndexRoute =
  LangTaberdokuTabersSudokuIndexRouteImport.update({
    id: '/taberdoku/tabers-sudoku/',
    path: '/taberdoku/tabers-sudoku/',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangTaberdokuTabersSudokuPlayRoute =
  LangTaberdokuTabersSudokuPlayRouteImport.update({
    id: '/taberdoku/tabers-sudoku/play',
    path: '/taberdoku/tabers-sudoku/play',
    getParentRoute: () => LangRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/eternity-ii': typeof EternityIiRoute
  '/the-taber-square': typeof TheTaberSquareRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/eternity-ii/play': typeof LangEternityIiPlayRoute
  '/$lang/the-taber-square/play': typeof LangTheTaberSquarePlayRoute
  '/$lang/the-tabers-star/play': typeof LangTheTabersStarPlayRoute
  '/$lang/eternity-ii/': typeof LangEternityIiIndexRoute
  '/$lang/taberdoku/': typeof LangTaberdokuIndexRoute
  '/$lang/the-taber-square/': typeof LangTheTaberSquareIndexRoute
  '/$lang/the-tabers-star/': typeof LangTheTabersStarIndexRoute
  '/$lang/taberdoku/murdoku/admin': typeof LangTaberdokuMurdokuAdminRoute
  '/$lang/taberdoku/murdoku/create': typeof LangTaberdokuMurdokuCreateRoute
  '/$lang/taberdoku/murdoku/play': typeof LangTaberdokuMurdokuPlayRoute
  '/$lang/taberdoku/star-battle/play': typeof LangTaberdokuStarBattlePlayRoute
  '/$lang/taberdoku/tabers-sudoku/play': typeof LangTaberdokuTabersSudokuPlayRoute
  '/$lang/taberdoku/murdoku/': typeof LangTaberdokuMurdokuIndexRoute
  '/$lang/taberdoku/star-battle/': typeof LangTaberdokuStarBattleIndexRoute
  '/$lang/taberdoku/tabers-sudoku/': typeof LangTaberdokuTabersSudokuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eternity-ii': typeof EternityIiRoute
  '/the-taber-square': typeof TheTaberSquareRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/eternity-ii/play': typeof LangEternityIiPlayRoute
  '/$lang/the-taber-square/play': typeof LangTheTaberSquarePlayRoute
  '/$lang/the-tabers-star/play': typeof LangTheTabersStarPlayRoute
  '/$lang/eternity-ii': typeof LangEternityIiIndexRoute
  '/$lang/taberdoku': typeof LangTaberdokuIndexRoute
  '/$lang/the-taber-square': typeof LangTheTaberSquareIndexRoute
  '/$lang/the-tabers-star': typeof LangTheTabersStarIndexRoute
  '/$lang/taberdoku/murdoku/admin': typeof LangTaberdokuMurdokuAdminRoute
  '/$lang/taberdoku/murdoku/create': typeof LangTaberdokuMurdokuCreateRoute
  '/$lang/taberdoku/murdoku/play': typeof LangTaberdokuMurdokuPlayRoute
  '/$lang/taberdoku/star-battle/play': typeof LangTaberdokuStarBattlePlayRoute
  '/$lang/taberdoku/tabers-sudoku/play': typeof LangTaberdokuTabersSudokuPlayRoute
  '/$lang/taberdoku/murdoku': typeof LangTaberdokuMurdokuIndexRoute
  '/$lang/taberdoku/star-battle': typeof LangTaberdokuStarBattleIndexRoute
  '/$lang/taberdoku/tabers-sudoku': typeof LangTaberdokuTabersSudokuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/eternity-ii': typeof EternityIiRoute
  '/the-taber-square': typeof TheTaberSquareRoute
  '/$lang/auth': typeof LangAuthRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/eternity-ii/play': typeof LangEternityIiPlayRoute
  '/$lang/the-taber-square/play': typeof LangTheTaberSquarePlayRoute
  '/$lang/the-tabers-star/play': typeof LangTheTabersStarPlayRoute
  '/$lang/eternity-ii/': typeof LangEternityIiIndexRoute
  '/$lang/taberdoku/': typeof LangTaberdokuIndexRoute
  '/$lang/the-taber-square/': typeof LangTheTaberSquareIndexRoute
  '/$lang/the-tabers-star/': typeof LangTheTabersStarIndexRoute
  '/$lang/taberdoku/murdoku/admin': typeof LangTaberdokuMurdokuAdminRoute
  '/$lang/taberdoku/murdoku/create': typeof LangTaberdokuMurdokuCreateRoute
  '/$lang/taberdoku/murdoku/play': typeof LangTaberdokuMurdokuPlayRoute
  '/$lang/taberdoku/star-battle/play': typeof LangTaberdokuStarBattlePlayRoute
  '/$lang/taberdoku/tabers-sudoku/play': typeof LangTaberdokuTabersSudokuPlayRoute
  '/$lang/taberdoku/murdoku/': typeof LangTaberdokuMurdokuIndexRoute
  '/$lang/taberdoku/star-battle/': typeof LangTaberdokuStarBattleIndexRoute
  '/$lang/taberdoku/tabers-sudoku/': typeof LangTaberdokuTabersSudokuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/eternity-ii'
    | '/the-taber-square'
    | '/$lang/auth'
    | '/$lang/'
    | '/$lang/eternity-ii/play'
    | '/$lang/the-taber-square/play'
    | '/$lang/the-tabers-star/play'
    | '/$lang/eternity-ii/'
    | '/$lang/taberdoku/'
    | '/$lang/the-taber-square/'
    | '/$lang/the-tabers-star/'
    | '/$lang/taberdoku/murdoku/admin'
    | '/$lang/taberdoku/murdoku/create'
    | '/$lang/taberdoku/murdoku/play'
    | '/$lang/taberdoku/star-battle/play'
    | '/$lang/taberdoku/tabers-sudoku/play'
    | '/$lang/taberdoku/murdoku/'
    | '/$lang/taberdoku/star-battle/'
    | '/$lang/taberdoku/tabers-sudoku/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eternity-ii'
    | '/the-taber-square'
    | '/$lang/auth'
    | '/$lang'
    | '/$lang/eternity-ii/play'
    | '/$lang/the-taber-square/play'
    | '/$lang/the-tabers-star/play'
    | '/$lang/eternity-ii'
    | '/$lang/taberdoku'
    | '/$lang/the-taber-square'
    | '/$lang/the-tabers-star'
    | '/$lang/taberdoku/murdoku/admin'
    | '/$lang/taberdoku/murdoku/create'
    | '/$lang/taberdoku/murdoku/play'
    | '/$lang/taberdoku/star-battle/play'
    | '/$lang/taberdoku/tabers-sudoku/play'
    | '/$lang/taberdoku/murdoku'
    | '/$lang/taberdoku/star-battle'
    | '/$lang/taberdoku/tabers-sudoku'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/eternity-ii'
    | '/the-taber-square'
    | '/$lang/auth'
    | '/$lang/'
    | '/$lang/eternity-ii/play'
    | '/$lang/the-taber-square/play'
    | '/$lang/the-tabers-star/play'
    | '/$lang/eternity-ii/'
    | '/$lang/taberdoku/'
    | '/$lang/the-taber-square/'
    | '/$lang/the-tabers-star/'
    | '/$lang/taberdoku/murdoku/admin'
    | '/$lang/taberdoku/murdoku/create'
    | '/$lang/taberdoku/murdoku/play'
    | '/$lang/taberdoku/star-battle/play'
    | '/$lang/taberdoku/tabers-sudoku/play'
    | '/$lang/taberdoku/murdoku/'
    | '/$lang/taberdoku/star-battle/'
    | '/$lang/taberdoku/tabers-sudoku/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  EternityIiRoute: typeof EternityIiRoute
  TheTaberSquareRoute: typeof TheTaberSquareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eternity-ii': {
      id: '/eternity-ii'
      path: '/eternity-ii'
      fullPath: '/eternity-ii'
      preLoaderRoute: typeof EternityIiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-taber-square': {
      id: '/the-taber-square'
      path: '/the-taber-square'
      fullPath: '/the-taber-square'
      preLoaderRoute: typeof TheTaberSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/auth': {
      id: '/$lang/auth'
      path: '/auth'
      fullPath: '/$lang/auth'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/eternity-ii/': {
      id: '/$lang/eternity-ii/'
      path: '/eternity-ii'
      fullPath: '/$lang/eternity-ii/'
      preLoaderRoute: typeof LangEternityIiIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/eternity-ii/play': {
      id: '/$lang/eternity-ii/play'
      path: '/eternity-ii/play'
      fullPath: '/$lang/eternity-ii/play'
      preLoaderRoute: typeof LangEternityIiPlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/': {
      id: '/$lang/taberdoku/'
      path: '/taberdoku'
      fullPath: '/$lang/taberdoku/'
      preLoaderRoute: typeof LangTaberdokuIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/the-taber-square/': {
      id: '/$lang/the-taber-square/'
      path: '/the-taber-square'
      fullPath: '/$lang/the-taber-square/'
      preLoaderRoute: typeof LangTheTaberSquareIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/the-taber-square/play': {
      id: '/$lang/the-taber-square/play'
      path: '/the-taber-square/play'
      fullPath: '/$lang/the-taber-square/play'
      preLoaderRoute: typeof LangTheTaberSquarePlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/the-tabers-star/': {
      id: '/$lang/the-tabers-star/'
      path: '/the-tabers-star'
      fullPath: '/$lang/the-tabers-star/'
      preLoaderRoute: typeof LangTheTabersStarIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/the-tabers-star/play': {
      id: '/$lang/the-tabers-star/play'
      path: '/the-tabers-star/play'
      fullPath: '/$lang/the-tabers-star/play'
      preLoaderRoute: typeof LangTheTabersStarPlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/murdoku/': {
      id: '/$lang/taberdoku/murdoku/'
      path: '/taberdoku/murdoku'
      fullPath: '/$lang/taberdoku/murdoku/'
      preLoaderRoute: typeof LangTaberdokuMurdokuIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/murdoku/admin': {
      id: '/$lang/taberdoku/murdoku/admin'
      path: '/taberdoku/murdoku/admin'
      fullPath: '/$lang/taberdoku/murdoku/admin'
      preLoaderRoute: typeof LangTaberdokuMurdokuAdminRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/murdoku/create': {
      id: '/$lang/taberdoku/murdoku/create'
      path: '/taberdoku/murdoku/create'
      fullPath: '/$lang/taberdoku/murdoku/create'
      preLoaderRoute: typeof LangTaberdokuMurdokuCreateRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/murdoku/play': {
      id: '/$lang/taberdoku/murdoku/play'
      path: '/taberdoku/murdoku/play'
      fullPath: '/$lang/taberdoku/murdoku/play'
      preLoaderRoute: typeof LangTaberdokuMurdokuPlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/star-battle/': {
      id: '/$lang/taberdoku/star-battle/'
      path: '/taberdoku/star-battle'
      fullPath: '/$lang/taberdoku/star-battle/'
      preLoaderRoute: typeof LangTaberdokuStarBattleIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/star-battle/play': {
      id: '/$lang/taberdoku/star-battle/play'
      path: '/taberdoku/star-battle/play'
      fullPath: '/$lang/taberdoku/star-battle/play'
      preLoaderRoute: typeof LangTaberdokuStarBattlePlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/tabers-sudoku/': {
      id: '/$lang/taberdoku/tabers-sudoku/'
      path: '/taberdoku/tabers-sudoku'
      fullPath: '/$lang/taberdoku/tabers-sudoku/'
      preLoaderRoute: typeof LangTaberdokuTabersSudokuIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/taberdoku/tabers-sudoku/play': {
      id: '/$lang/taberdoku/tabers-sudoku/play'
      path: '/taberdoku/tabers-sudoku/play'
      fullPath: '/$lang/taberdoku/tabers-sudoku/play'
      preLoaderRoute: typeof LangTaberdokuTabersSudokuPlayRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAuthRoute: typeof LangAuthRoute
  LangIndexRoute: typeof LangIndexRoute
  LangEternityIiPlayRoute: typeof LangEternityIiPlayRoute
  LangTheTaberSquarePlayRoute: typeof LangTheTaberSquarePlayRoute
  LangTheTabersStarPlayRoute: typeof LangTheTabersStarPlayRoute
  LangEternityIiIndexRoute: typeof LangEternityIiIndexRoute
  LangTaberdokuIndexRoute: typeof LangTaberdokuIndexRoute
  LangTheTaberSquareIndexRoute: typeof LangTheTaberSquareIndexRoute
  LangTheTabersStarIndexRoute: typeof LangTheTabersStarIndexRoute
  LangTaberdokuMurdokuAdminRoute: typeof LangTaberdokuMurdokuAdminRoute
  LangTaberdokuMurdokuCreateRoute: typeof LangTaberdokuMurdokuCreateRoute
  LangTaberdokuMurdokuPlayRoute: typeof LangTaberdokuMurdokuPlayRoute
  LangTaberdokuStarBattlePlayRoute: typeof LangTaberdokuStarBattlePlayRoute
  LangTaberdokuTabersSudokuPlayRoute: typeof LangTaberdokuTabersSudokuPlayRoute
  LangTaberdokuMurdokuIndexRoute: typeof LangTaberdokuMurdokuIndexRoute
  LangTaberdokuStarBattleIndexRoute: typeof LangTaberdokuStarBattleIndexRoute
  LangTaberdokuTabersSudokuIndexRoute: typeof LangTaberdokuTabersSudokuIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAuthRoute: LangAuthRoute,
  LangIndexRoute: LangIndexRoute,
  LangEternityIiPlayRoute: LangEternityIiPlayRoute,
  LangTheTaberSquarePlayRoute: LangTheTaberSquarePlayRoute,
  LangTheTabersStarPlayRoute: LangTheTabersStarPlayRoute,
  LangEternityIiIndexRoute: LangEternityIiIndexRoute,
  LangTaberdokuIndexRoute: LangTaberdokuIndexRoute,
  LangTheTaberSquareIndexRoute: LangTheTaberSquareIndexRoute,
  LangTheTabersStarIndexRoute: LangTheTabersStarIndexRoute,
  LangTaberdokuMurdokuAdminRoute: LangTaberdokuMurdokuAdminRoute,
  LangTaberdokuMurdokuCreateRoute: LangTaberdokuMurdokuCreateRoute,
  LangTaberdokuMurdokuPlayRoute: LangTaberdokuMurdokuPlayRoute,
  LangTaberdokuStarBattlePlayRoute: LangTaberdokuStarBattlePlayRoute,
  LangTaberdokuTabersSudokuPlayRoute: LangTaberdokuTabersSudokuPlayRoute,
  LangTaberdokuMurdokuIndexRoute: LangTaberdokuMurdokuIndexRoute,
  LangTaberdokuStarBattleIndexRoute: LangTaberdokuStarBattleIndexRoute,
  LangTaberdokuTabersSudokuIndexRoute: LangTaberdokuTabersSudokuIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  EternityIiRoute: EternityIiRoute,
  TheTaberSquareRoute: TheTaberSquareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
